language: go
sudo: false

cache:
  go: true
  directories:
  - "$HOME/.cache"
go:
- master
- "1.12"
- "1.11"
- 1.10.x
- 1.9
- 1.8
- 1.7
- 1.6

matrix:
  include:
  - go: master
    env: task=clean
script: ./script/${task:-test}
after_success: if [[ -z "$task" ]] ; then bash <(curl -s https://codecov.io/bash) ; fi
