language: go
sudo: false

cache:
  go: true
  directories:
    - $HOME/.cache
    - $HOME/gopath/pkg/mod
go:
- 1.6
- 1.7
- 1.8
- 1.9
- "1.10"
- "1.11"
- "1.12"
- 1.x

matrix:
  include:
  - go: master
    env: task=clean
script: ./script/${task:-test}
before_cache: rm -f $HOME/.cache/go-build/log.txt

after_success: if [[ -z "$task" ]] ; then bash <(curl -s https://codecov.io/bash) ; fi
