#!/bin/bash
set -eu
err=0

# developer: commit fixes
# CI: fail build
# smarter CI: send patch (pull request)

if ! git diff --exit-code >/dev/null ; then
  echo "$0: sorry, this script needs clean git tree, try git stash" >&2
  exit 1
fi

echo "$0: go mod tidy"
go mod tidy
git diff --exit-code || err=1

echo "$0: go fix"
go fix ./...
git diff --exit-code || err=1

confirm() {
  local reply
  local prompt="$1"
  read -n1 -p "$prompt" -t31 reply >&2
  echo "" >&2
  local rc=0
  local default_y=" \[Yn\] $"
  if [[ -z "$reply" ]] && [[ "$prompt" =~ $default_y ]] ; then
    reply="y"
  fi
  [[ "$reply" != "y" ]] && rc=1
  return $rc
}

if ! golangci-lint -h &>/dev/null ; then
  echo "$0: golangci-lint is not installed; CI should just work" >&2
  if confirm "Local dev? Install golangci-lint? [yN] " ; then
    (
      set -eux
      cd $(mktemp -d)
      export GO111MODULE=on
      go mod init tmp
      go get github.com/golangci/golangci-lint/cmd/golangci-lint
      rm -rf $PWD
    )
  fi
fi
echo "$0: golangci-lint run"
golangci-lint run

exit $err
